const translations = {
  ru: {
    contacts: "Контакты",
    login: "Войти",
    register: "Зарегистрироваться",
    services: "Услуги",
    projects: "Проекты",
    our: "Наши возможности",
    about1: "TapLogic - это команда профессионалов, специализирующихся на создании инновационных мобильных приложений. Наша компания была основана в 2019 году с целью предоставления высококачественных IT-решений для бизнеса любого масштаба.",
    about2: "Мы сочетаем креативный подход с техническим мастерством, чтобы создавать продукты, которые не только решают бизнес-задачи, но и обеспечивают исключительный пользовательский опыт.",
    banner: "Проектирование, разработка и развитие мобильных приложений",
    request: "Оставить заявку",
    about: "О нас",
    ct1: "Мобильная разработка",
    ct2: "UI/UX дизайн",
    ct3: "Backend разработка",
    ct4: "Аналитика",
    ct5: "Безопасность",
    ct6: "Поддержка",
    c1: "Создание нативных и кроссплатформенных приложений для iOS и Android с использованием современных технологий.",
    c2: "Проектирование интуитивно понятных интерфейсов с акцентом на пользовательский опыт и визуальную привлекательность.",
    c3: "Разработка надежных серверных решений и API для обеспечения бесперебойной работы мобильных приложений",
    c4: "Интеграция систем аналитики для отслеживания ключевых метрик и оптимизации бизнес-процессов.",
    c5: "Реализация комплексных мер защиты данных и соответствие международным стандартам безопасности.",
    c6: "Пост-релизное сопровождение, обновления и техническая поддержка вашего приложения.",
    s1: "Завершенных проектов",
    s2: "Постоянных клиентов",
    s3: "Лет на рынке",
    geo: "ул. Розыбакиева, 113, Алматы",
    call: "Заказать звонок",
    idea: "У тебя есть идея? Мы воплотим её в жизнь.",
    cont: "Связаться с нами",
    page1: "до 4 страниц приложения",
    page2: "до 8 страниц приложения",
    page3: "до 12 страниц приложения",
    p11:"за 10 дней",
    p22: "за 1 месяц",
    p33: "за 2 месяца",
    package: "ВЫБЕРИ ПАКЕТ ДЛЯ РАЗРАБОТКИ ПРИЛОЖЕНИЯ ДЛЯ IOS И ANDROID",
    price1: "250тыс. Тенге",
    price2: "500тыс. Тенге",
    price3: "750тыс. Тенге",
    limit1: "Техподдержка 7 дней",
    limit2: "Техподдержка 1 месяц",
    limit3: "Техподдержка 3 месяца",
    desc1: "Адаптивный дизайн",
    desc2: "Мультиязычность",
    desc3: "Админ панель",
    rec: "ЗАКАЗАТЬ",
    step1: "Обсуждение будущего продукта",
    step3: "Разработка приложения",
    step2: "Создание Дизайна и прототипа",
    step4: "Тестирование и запуск",
    st1: "Вместе определим цели и приоритеты, разобьём проект на этапы и определим необходимый базовый функционал МУР для быстрой проверки гипотез вашей бизнес-модели. Составим детальное Техническое задание и предварительное коммерческое предложение на каждый из этапов создания/развития проекта.",
    st2: "Создадим дизайн и кликабельный прототип интерфейса будущего сервиса. Мы воспроизведём структуру сервиса и сможем вместе продумать основные сценарии пользовательского поведения. Прототипирование позволит учесть максимум мелочей, тем самым сэкономив часы на дальнейших этапах.",
    st3: "На этом этапе мы реализуем весь запланированный функционал вашего приложения. Используем современные технологии и методологии разработки, чтобы обеспечить высокое качество кода и производительность приложения.",
    st4: "Проведём всестороннее тестирование приложения, устраним возможные ошибки и подготовим его к публикации в магазинах приложений. После запуска обеспечим техническую поддержку и дальнейшее развитие проекта.",
    feedback1: "Уже пробовали наш продукт?",
    feedback2: "Поделитесь своим опытом и помогите нам стать лучше",
    feedback3: "Оставить отзыв",
    n2: "Базовый",
    n3: "Оптимальный",
    steps: "Этапы работы",
    pro: "НАШИ ПОСЛЕДНИЕ РАБОТЫ",
    cap: "Возможности:",
    download: "Скачать приложение",
    steps:"Этапы работы",

        // 7Food
    "7food": "Инновационная платформа для бесконтактных покупок, разработанная в партнерстве с Coca Cola. Приложение позволяет совершать покупки без касс и очередей, используя передовые технологии.",
        "7f1": "Поиск магазинов-партнеров на интерактивной карте",
        "7f2": "Удобный выбор товаров через мобильное приложение",
        "7f3": "Автоматическое оформление заказа и бесшовная оплата",
        "7f4": "Принцип работы: \"Открыл - Взял товар - Закрыл\"",
        "7f5": "Компьютерное зрение с ИИ для распознавания товаров",

        // SDU Portal
        sdu: "Мобильное решение для университета SDU, объединяющее студентов и преподавателей в едином цифровом пространстве. Приложение значительно упрощает учебный процесс.",
        sdu1: "Доступ к учебным материалам и расписанию",
        sdu2: "Регистрация на курсы и контроль успеваемости",
        sdu3: "Система электронного посещения занятий",
        sdu4: "Интегрированный календарь учебных событий",
        sdu5: "Раздельные интерфейсы для студентов и преподавателей",

        // ToyVille
        toy: "Уникальный маркетплейс детских товаров с абонементной системой. В настоящее время ведется разработка второй версии приложения с расширенным функционалом.",
        toy1: "Обширный каталог игрушек и детских товаров",
        toy2: "Гибкая система абонементов и бонусных программ",
        toy3: "Безопасная оплата и отслеживание заказов",
        toy4: "Интеграция с товарами и услугами партнеров",
        toy5: "Персонализированные рекомендации",

        // OnlineBus
        bus: "Комплексное решение для бронирования междугородних автобусных рейсов. Платформа объединяет пассажиров и перевозчиков, делая путешествия комфортнее.",
        bus1: "Поиск и сравнение автобусных рейсов",
        bus2: "Онлайн-бронирование и выбор мест",
        bus3: "Безопасные платежи и история поездок",
        bus4: "Уведомления об изменениях расписания",
        bus5: "Специальный интерфейс для перевозчиков",

        // Narxoz
        narxoz: "Официальное мобильное приложение университета Narxoz, созданное для удобства студентов. Все важные академические сервисы теперь доступны в одном месте.",
        nar1: "Персонализированная лента новостей и объявлений",
        nar2: "Доступ к учебным материалам и заданиям",
        nar3: "Подача заявлений (включая общежитие)",
        nar4: "Электронное портфолио студента",
        nar5: "Интеграция с внутренними системами вуза",

    // Tags
    bis: "Бизнес анализ",
    des: "UI-UX Дизайн",
    ios: "iOS",
    and: "Android",
    qa: "QA",
    "1c": "1C интеграция ",
    testi: "НАШИ КЛИЕНТЫ",
        p1: "Даниил Корнеев",
        per1: "Директор, 7Food",
        feed1: "TapLogic создал для нас революционное приложение, которое полностью изменило подход к покупкам. Технология компьютерного зрения работает безупречно, а пользователи в восторге от удобства.",
        p2: "Алина Романова",
        per2: "Руководитель IT, SDU",
        feed2: "Работа с TapLogic над мобильным порталом для нашего университета была исключительно продуктивной. Они учли все наши пожелания и создали приложение, которое действительно облегчило жизнь студентам и преподавателям.",
        p3: "Бекзат Ахметов",
        per3: "Основатель, ToyVille",
        feed3: "Команда TapLogic не просто разработала приложение — они помогли нам создать цифровую экосистему для нашего бизнеса. Абонементная система работает идеально, и мы уже видим рост лояльности клиентов.",
        p4: "Алия Кенжебаева",
        per4: "Менеджер проектов, OnlineBus",
        feed4: "Благодаря TapLogic мы смогли вывести наш сервис бронирования автобусов на новый уровень. Приложение стабильное, удобное и уже получило множество положительных отзывов от наших клиентов.",
        p5: "Андрей Ефимов",
        per5: "IT директор, Narxoz",
        feed5: "Приложение, разработанное TapLogic, стало неотъемлемой частью цифровой инфраструктуры нашего университета. Интеграция с внутренними системами выполнена на высшем уровне.",
        p6: "Аружан Төлегенова",
        per6: "Маркетинг директор, 7Food",
        feed6: "Сотрудничество с TapLogic превзошло все наши ожидания. Приложение не только функциональное, но и имеет потрясающий дизайн, что значительно повысило вовлеченность наших пользователей.",
        close:"Закрыть профиль",
        edit:"Редактировать профиль",
        profiles:"Личный кабинет",
        welcome:"Добро пожаловать в личный кабинет",
        lg1:"Вход",
        lg2:"Пароль",
        lg3:"Войти",
        lg4:"Успешный вход! Перенаправление...",
        lg5:"Зарегистрируйтесь",
        rg1:"Регистрация",
        rg2:"Фамилия",
        rg4:"Телефон",
        rg5:"Название компании",
        rg6:"Описание проекта",
        rg8:"Успешно зарегистрирован! Перенаправление...",
        rg9:"Войдите",
        rq1:"Оставить заявку",
        rq2:"Тема",
        rg3:"Сообщение",
        rq4:"Отправить",
        rq5:"Заявка успешно отправлена! Перенаправление...",
        rg10:"Имя",
        list:"Ваш список заявок пуст",
        title:"TapLogic - Разработка мобильных приложений"

  },
  en: {
    contacts: "Contacts",
    login: "Login",
    register: "Register",
    services: "Services",
    projects: "Projects",
    our: "Our capabilities",
    about1: "TapLogic is a team of professionals specializing in the creation of innovative mobile applications. Our company was founded in 2019 to provide high-quality IT solutions for businesses of any size.",
    about2: "We combine a creative approach with technical expertise to build products that not only solve business problems but also deliver an exceptional user experience.",
    banner: "Design, development, and growth of mobile applications",
    request: "Submit a request",
    about: "About us",
    ct1: "Mobile development",
    ct2: "UI/UX design",
    ct3: "Backend development",
    ct4: "Analytics",
    ct5: "Security",
    ct6: "Support",
    c1: "Development of native and cross-platform applications for iOS and Android using modern technologies.",
    c2: "Designing intuitive interfaces with a focus on user experience and visual appeal.",
    c3: "Building reliable backend solutions and APIs to ensure seamless mobile app performance.",
    c4: "Integrating analytics systems to track key metrics and optimize business processes.",
    c5: "Implementing comprehensive data protection measures and complying with international security standards.",
    c6: "Post-release support, updates, and technical maintenance for your application.",
    s1: "Completed projects",
    s2: "Regular clients",
    s3: "Years in the market",
    geo: "113 Rozybakiev St., Almaty",
    call: "Order a call",
    idea: "Do you have an idea? We will bring it to life.",
    cont: "Contact us",
    page1: "up to 4 app pages",
    page2: "up to 8 app pages",
    page3: "up to 12 app pages",
    p11: "in 10 days",
    p22: "in 1 month",
    p33: "in 2 months",
    n2: "Base",
    n3 :"Optimal",
    package: "CHOOSE A PACKAGE TO DEVELOP AN IOS & ANDROID APP",
    price1: "250k Tenge",
    price2: "500k Tenge",
    price3: "750k Tenge",
    limit1: "7 days support",
    limit2: "1 month support",
    limit3: "3 months support",
    desc1: "Responsive design",
    desc2: "Multilingual",
    desc3: "Admin panel",
    rec: "ORDER NOW",
    st1: "We will define the goals and priorities together, break down the project into stages, and determine the required MVP functionality to test your business model. We will prepare a detailed technical specification and a commercial proposal for each stage.",
st2: "We will create a design and a clickable interface prototype of the future service. Together, we will develop the structure and key user scenarios. Prototyping allows us to consider details early and save time in later stages.",
st3: "We will implement all planned functionality using modern technologies and development methodologies to ensure high code quality and performance.",
st4: "We will conduct full testing, fix any bugs, and prepare the app for publishing in app stores. After launch, we will provide technical support and further project development.",
    step1: "Discussing the future product",
    step2: "Design and prototyping",
    step3: "App development",
    step4: "Testing and launch",
    steps:"Stages of work",
    
    feedback1: "Have you tried our product?",
    feedback2: "Share your experience and help us improve",
    feedback3: "Leave a review",
     pro: "OUR LATEST PROJECTS",
        cap: "Features:",
        download: "Download App",

        // 7Food
        "7food": "An innovative platform for contactless shopping, developed in partnership with Coca Cola. The app enables cashierless, queue-free purchases using cutting-edge technologies.",
        "7f1": "Search for partner stores on an interactive map",
        "7f2": "Convenient product selection via mobile app",
        "7f3": "Automatic checkout and seamless payment",
        "7f4": "Working principle: \"Open - Take item - Close\"",
        "7f5": "AI-powered computer vision for product recognition",

        // SDU Portal
        sdu: "A mobile solution for SDU University that connects students and teachers in a unified digital space. The app greatly simplifies the learning process.",
        sdu1: "Access to study materials and schedule",
        sdu2: "Course registration and performance tracking",
        sdu3: "Electronic attendance system",
        sdu4: "Integrated academic events calendar",
        sdu5: "Separate interfaces for students and teachers",

        // ToyVille
        toy: "A unique kids product marketplace with a subscription model. The second version of the app is currently under development with extended features.",
        toy1: "Extensive catalog of toys and kids products",
        toy2: "Flexible subscription and bonus systems",
        toy3: "Secure payments and order tracking",
        toy4: "Integration with partner goods and services",
        toy5: "Personalized recommendations",

        // OnlineBus
        bus: "A comprehensive solution for intercity bus trip bookings. The platform connects passengers and carriers to make travel more convenient.",
        bus1: "Search and compare bus routes",
        bus2: "Online booking and seat selection",
        bus3: "Secure payments and trip history",
        bus4: "Schedule change notifications",
        bus5: "Special interface for bus carriers",

        // Narxoz
        narxoz: "The official mobile app of Narxoz University, designed for student convenience. All essential academic services are now in one place.",
        nar1: "Personalized news and announcements feed",
        nar2: "Access to study materials and assignments",
        nar3: "Application submission (including dormitory)",
        nar4: "Electronic student portfolio",
        nar5: "Integration with the university's internal systems",

        
        bis: "Business Analysis",
        des: "UI-UX Design",
        ios: "iOS",
        and: "Android",
        qa: "QA",
        "1c": "1C Integration",
        testi: "OUR CLIENTS",
        p1: "Daniil Korneev",
        per1: "Director, 7Food",
        feed1: "TapLogic created a revolutionary app for us that completely changed the way we shop. The computer vision technology works flawlessly, and users are thrilled with its convenience.",
        p2: "Alina Romanova",
        per2: "Head of IT, SDU",
        feed2: "Working with TapLogic on our university's mobile portal was extremely productive. They considered all our requests and created an app that truly eased the life of students and teachers.",
        p3: "Bekzat Akhmetov",
        per3: "Founder, ToyVille",
        feed3: "The TapLogic team didn't just develop an app – they helped us create a digital ecosystem for our business. The subscription system works perfectly, and we already see increased customer loyalty.",
        p4: "Aliya Kenzhebaeva",
        per4: "Project Manager, OnlineBus",
        feed4: "Thanks to TapLogic, we were able to take our bus booking service to the next level. The app is stable, user-friendly, and has received many positive reviews from our clients.",
        p5: "Andrey Efimov",
        per5: "IT Director, Narxoz",
        feed5: "The app developed by TapLogic has become an integral part of our university's digital infrastructure. Integration with internal systems is executed at the highest level.",
        p6: "Aruzhan Tolegenova",
        per6: "Marketing Director, 7Food",
        feed6: "Our collaboration with TapLogic exceeded all our expectations. The app is not only functional but also has an amazing design, which significantly increased user engagement.",
        close: "Close Profile",
    edit: "Edit Profile",
    profiles: "Profile",
    welcome: "Welcome to your profile",
    lg1: "Login",
    lg2: "Password",
    lg3: "Sign In",
    lg4: "Successfully logged in! Redirecting...",
    lg5: "Register",
    rg1: "Registration",
    rg2: "Last Name",
    rg4: "Phone",
    rg5: "Company Name",
    rg6: "Project Description",
    rg8: "Successfully registered! Redirecting...",
    rg9: "Login",
    rq1: "Submit a Request",
    rq2: "Subject",
    rg3: "Message",
    rq4: "Send",
    rq5: "Request successfully sent! Redirecting...",
    rg10: "First Name",
    list: "Your request list is empty",
    title:"TapLogic - Mobile app development"
    

  },
  kz: {
    contacts: "Байланыс",
    login: "Кіру",
    register: "Тіркелу",
    services: "Қызметтер",
    projects: "Жобалар",
    our: "Біздің мүмкіндіктер",
    about1: "TapLogic — инновациялық мобильді қосымшаларды жасауға маманданған кәсіби команда. Біздің компания 2019 жылы кез келген көлемдегі бизнеске жоғары сапалы IT-шешімдер ұсыну мақсатында құрылды.",
    about2: "Біз шығармашылық тәсілді техникалық шеберлікпен біріктіре отырып, тек бизнес-мәселелерді шешіп қана қоймай, ерекше пайдаланушы тәжірибесін ұсынатын өнімдер жасаймыз.",
    banner: "Мобильді қосымшаларды жобалау, әзірлеу және дамыту",
    request: "Өтінім қалдыру",
    about: "Біз туралы",
    ct1: "Мобильді әзірлеу",
    ct2: "UI/UX дизайн",
    ct3: "Backend әзірлеу",
    ct4: "Аналитика",
    ct5: "Қауіпсіздік",
    ct6: "Қолдау",
    c1: "Заманауи технологияларды қолдана отырып, iOS және Android үшін нативті және кросс-платформалық қосымшаларды жасау.",
    c2: "Пайдаланушы тәжірибесі мен визуалды тартымдылыққа баса назар аудара отырып, түсінікті интерфейстерді жобалау.",
    c3: "Мобильді қосымшалардың үздіксіз жұмысын қамтамасыз ету үшін сенімді сервер шешімдері мен API әзірлеу.",
    c4: "Негізгі метрикаларды қадағалау және бизнес-процестерді оңтайландыру үшін аналитика жүйелерін біріктіру.",
    c5: "Деректерді кешенді қорғау шараларын жүзеге асыру және халықаралық қауіпсіздік стандарттарына сәйкестік.",
    c6: "Қосымшаңызға пост-релиздік қолдау, жаңартулар және техникалық көмек көрсету.",
    s1: "Аяқталған жобалар",
    s2: "Тұрақты клиенттер",
    s3: "Нарықтағы жылдар",
    geo: "Розыбакиев көшесі, 113, Алматы",
    call: "Қоңырауға тапсырыс беру",
    idea: "Сенде идея бар ма? Біз оны жүзеге асырамыз.",
    cont: "Бізбен байланысу",
    page1: "қосымшаның 4 бетіне дейін",
    page2: "қосымшаның 8 бетіне дейін",
    page3: "қосымшаның 12 бетіне дейін",
    p11: "10 күнде",
    p22: "1 айда",
    p33: "2 айда",
    n2: "Стандартты",
    n3: "Тиімді",
    package: "IOS және ANDROID үшін ҚОСЫМША ДАЙЫНДАУ ПАКЕТІН ТАҢДАҢЫЗ",
    price1: "250 мың теңге",
    price2: "500 мың теңге",
    price3: "750 мың теңге",
    limit1: "7 күн техникалық қолдау",
    limit2: "1 ай техникалық қолдау",
    limit3: "3 ай техникалық қолдау",
    desc1: "Адаптивті дизайн",
    desc2: "Көптілділік",
    desc3: "Админ панель",
    rec: "Тапсырыс беру",
    step1: "Болашақ өнімді талқылау",
    step2: "Дизайн және прототип жасау",
    step3: "Қосымшаны әзірлеу",
    step4: "Тестілеу және іске қосу",
    st1: "Мақсаттар мен басымдықтарды бірге анықтаймыз, жобаны кезеңдерге бөліп, MVP функционалын анықтаймыз. Жоба үшін техникалық тапсырма мен коммерциялық ұсыныс жасаймыз.",
st2: "Болашақ сервис дизайны мен интерфейсінің кликабельді прототипін жасаймыз. Құрылым мен қолданушы сценарийлерін бірге ойластырамыз. Прототип көп уақыт үнемдеуге көмектеседі.",
st3: "Қосымшаның барлық жоспарланған функцияларын жүзеге асырамыз. Жоғары сапа мен өнімділікке қол жеткізу үшін заманауи технологиялар мен әдістерді қолданамыз.",
st4: "Қосымшаны толықтай тексереміз, қателерді түзетеміз және оны дүкендерге жариялауға дайындаймыз. Іске қосқаннан кейін техникалық қолдау мен дамыту қызметтерін ұсынамыз.",
    
    feedback1: "Біздің өнімді қолданып көрдіңіз бе?",
    feedback2: "Тәжірибеңізбен бөлісіп, бізге жақсартуға көмектесіңіз",
    feedback3: "Пікір қалдыру",
    pro: "БІЗДІҢ СОҢҒЫ ЖҰМЫСТАРЫМЫЗ",
    cap: "Мүмкіндіктері:",
    download: "Қолданбаны жүктеу",
    steps:"Жұмыс кезеңдері",
    // 7Food
        "7food": "Coca Cola компаниясымен бірлесіп жасалған, кассасыз және кезексіз сатып алуға мүмкіндік беретін инновациялық платформа. Қолданба алдыңғы қатарлы технологияларды пайдаланады.",
        "7f1": "Интерактивті картадағы серіктес дүкендерді іздеу",
        "7f2": "Мобильді қосымша арқылы ыңғайлы тауар таңдау",
        "7f3": "Тапсырысты автоматты рәсімдеу және үздіксіз төлем",
        "7f4": "Жұмыс принципі: «Аш - Тауарды ал - Жаб»",
        "7f5": "Жасанды интеллектпен жабдықталған компьютерлік көру жүйесі",

        // SDU Portal
        sdu: "SDU университетінің студенттері мен оқытушыларын біріктіретін мобильді шешім. Қолданба оқу процесін айтарлықтай жеңілдетеді.",
        sdu1: "Оқу материалдарына және кестеге қол жеткізу",
        sdu2: "Курстарға тіркелу және үлгерімді бақылау",
        sdu3: "Электрондық қатысу жүйесі",
        sdu4: "Оқу іс-шараларының біріктірілген күнтізбесі",
        sdu5: "Студенттер мен оқытушыларға арналған бөлек интерфейстер",

        // ToyVille
        toy: "Абонементтік жүйесі бар балалар тауарларының бірегей маркетплейсі. Қосымшаның екінші нұсқасы кеңейтілген функционалмен әзірленуде.",
        toy1: "Ойыншықтар мен балалар тауарларының кең каталогы",
        toy2: "Икемді абонементтер мен бонус бағдарламалары",
        toy3: "Қауіпсіз төлем және тапсырыстарды бақылау",
        toy4: "Серіктес тауарлар мен қызметтерге интеграция",
        toy5: "Жеке ұсыныстар",

        // OnlineBus
        bus: "Қалааралық автобус рейстерін брондау үшін кешенді шешім. Платформа жолаушылар мен тасымалдаушыларды біріктіреді, саяхатты ыңғайлы етеді.",
        bus1: "Автобус рейстерін іздеу және салыстыру",
        bus2: "Онлайн брондау және орын таңдау",
        bus3: "Қауіпсіз төлемдер және сапар тарихы",
        bus4: "Жоспар өзгерістері туралы хабарландырулар",
        bus5: "Тасымалдаушыларға арналған арнайы интерфейс",

        // Narxoz
        narxoz: "Narxoz университетінің ресми мобильді қосымшасы, студенттер үшін ыңғайлы жасалған. Барлық маңызды академиялық қызметтер бір жерде.",
        nar1: "Жеке жаңалықтар мен хабарландырулар лентасы",
        nar2: "Оқу материалдары мен тапсырмаларға қол жеткізу",
        nar3: "Өтініштерді беру (общежитие қоса алғанда)",
        nar4: "Электрондық студент портфолиосы",
        nar5: "Университет ішкі жүйелерімен интеграция",

        // Tags
        bis: "Бизнес талдау",
        des: "UI-UX дизайн",
        ios: "iOS",
        and: "Android",
        qa: "QA",
        "1c": "1C интеграция",
        testi: "БІЗДІҢ КЛИЕНТТЕР",
p1: "Даниил Корнеев",
per1: "Директор, 7Food",
feed1: "TapLogic біз үшін сауда жасау тәсілін түбегейлі өзгерткен революциялық қосымша жасады. Компьютерлік көру технологиясы мінсіз жұмыс істейді, ал пайдаланушылар ыңғайлылыққа риза.",
p2: "Алина Романова",
per2: "IT бөлімінің басшысы, SDU",
feed2: "TapLogic-пен университетіміздің мобильді порталы бойынша жұмыс өте тиімді болды. Олар біздің барлық талаптарымызды ескеріп, студенттер мен оқытушылардың өмірін жеңілдететін қосымша жасады.",
p3: "Бекзат Ахметов",
per3: "Құрушы, ToyVille",
feed3: "TapLogic командасы жай ғана қосымша жасап қойған жоқ – олар біздің бизнесімізге арналған цифрлық экожүйе құруға көмектесті. Абонемент жүйесі өте жақсы жұмыс істейді, және біз клиенттердің адалдығының артқанын байқап отырмыз.",
p4: "Алия Кенжебаева",
per4: "Жоба менеджері, OnlineBus",
feed4: "TapLogic-тің арқасында біз автобус брондау қызметімізді жаңа деңгейге шығара алдық. Қосымша тұрақты, ыңғайлы және клиенттерімізден көптеген оң пікірлер алды.",
p5: "Андрей Ефимов",
per5: "IT директоры, Narxoz",
feed5: "TapLogic жасаған қосымша университетіміздің цифрлық инфрақұрылымының ажырамас бөлігіне айналды. Ішкі жүйелермен интеграция ең жоғары деңгейде орындалды.",
p6: "Аружан Төлегенова",
per6: "Маркетинг директоры, 7Food",
feed6: "TapLogic-пен серіктестік біздің барлық үмітімізден асып түсті. Қосымша тек функционалды ғана емес, сонымен қатар таңғажайып дизайнға ие, бұл пайдаланушылардың қызығушылығын едәуір арттырды.",
close: "Профильді жабу",
    edit: "Профильді өңдеу",
    profiles: "Жеке кабинет",
    welcome: "Жеке кабинетке қош келдіңіз",
    lg1: "Кіру",
    lg2: "Құпиясөз",
    lg3: "Кіру",
    lg4: "Сәтті кірдіңіз! Бағытталуда...",
    lg5: "Тіркеліңіз",
    rg1: "Тіркелу",
    rg2: "Тегі",
    rg4: "Телефон",
    rg5: "Компания атауы",
    rg6: "Жоба сипаттамасы",
    rg8: "Сәтті тіркелдіңіз! Бағытталуда...",
    rg9: "Кіру",
    rq1: "Өтініш қалдыру",
    rq2: "Тақырып",
    rg3: "Хабарлама",
    rq4: "Жіберу",
    rq5: "Өтініш сәтті жіберілді!Бағытталуда...",
    rg10: "Аты",
    list: "Сіздің өтініштер тізіміңіз бос",
    title:"TapLogic - Мобильді қосымшаларды әзірлеу"
    
    

    
  }
};

function changeLanguage(lang) {
  // 1. Сохраняем язык в localStorage
  localStorage.setItem("lang", lang);

  // 2. Обновляем отображение текущего языка в меню
  const currentLangSpan = document.getElementById("current-language");
  const langNames = {
    ru: "Русский",
    kz: "Қазақша",
    en: "English"
  };
  if (currentLangSpan) {
    currentLangSpan.innerHTML = langNames[lang] + ' <i class="fas fa-chevron-down"></i>';
  }

  // 3. Переводим весь сайт
  document.querySelectorAll("[data-translate]").forEach(elem => {
    const key = elem.getAttribute("data-translate");
    elem.textContent = translations[lang][key] || key;
  });
}

// Загружаем язык при открытии страницы
document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("lang") || "ru";
  changeLanguage(savedLang);
});

